### ISSUE TITLE
bug: out-of-bounds read when using inline assembly code path

### ISSUE THREAD

**Issue by mayeut** [aklomp/base64#111]
While upgrading base64 in a project I'm working on, valgrind started to report out-of-bounds read in the optimized encoding functions.
Those are now using the inline assembly code path instead of the intrinsics code path.

A draft PR with a reproducer will follow (I do not plan to fix this though).

**Comment by aklomp** [comment]
This is probably due to choosing the wrong [cutoff value](https://github.com/aklomp/base64/blob/master/lib/arch/avx2/enc_loop_asm.c#L129) for the source length. I'll look into it later. Thanks for reporting.

**Comment by aklomp** [comment]
Found the bug. It's in [this](https://github.com/aklomp/base64/blob/master/lib/arch/ssse3/enc_loop_asm.c#L137) calculation. Note how it differs (mistakenly) from the [equivalent calculation](https://github.com/aklomp/base64/blob/master/lib/arch/ssse3/enc_loop.c#L31) in the non-asm code.

When calculating the number of rounds that the SIMD encoder can complete, we need to adjust for the fact that rounds consume 12 bytes of inputs, but the read size is 16 bytes. That's why we should subtract four bytes from the input size to ensure that a 16-byte read will not extend past the input buffer.

I'll fix and merge this after I review your pull request. The changes to CI in the pull request should validate the fix.

**Comment by aklomp** [comment]
The bug occurred because the first encoder to be converted to inline asm was the AVX2 encoder. That codec [treats the first round specially](https://github.com/aklomp/base64/blob/master/lib/arch/avx2/enc_loop.c#L42) by reading it at an offset of +0 bytes, while all following rounds are read at an offset of -4 bytes. This led me to believe that subtracting the four bytes only applied to that codec, and not to AVX and SSSE3, which is why I left it out from those codecs.
