### ISSUE TITLE
When is the new release expected?

### ISSUE THREAD

**Issue by bharat42** [aklomp/base64#51]
I see a lot of commits since last release so I was interested to know by when you are going to publish a new release.

**Comment by aklomp** [comment]
Good question, it has indeed been a while. I don't have any release planned, nor do I have a roadmap for upcoming releases, but I do think that since this library has been stable (read: stagnant) for so long, it's probably time to place a tag on it.

However, I won't do that immediately because I have a few cleanup commits that I'd like to apply first. That could take a while because I have a lot of projects and this one has fallen behind in the to-do list, so feel free to remind me.

**Comment by aklomp** [comment]
I've picked up work on this library again, and plan to make a new release in the near future. This release will include the current code, plus extended CI checks (issue #53) and some code cleanups which have no functional impact. This release will put a label on the code that everyone has been using for the last few years.

After that, I want to take some freedoms to make larger changes, such as the way in which the codecs are structured or symbols are hidden, and introduce new features like cmake support. But that's all longer term.

**Comment by bharat42** [comment]
Thanks for the update Alfred.

**Comment by aklomp** [comment]
Just release v0.4.0.
